pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "harsha6798/robot-app-payment-image:${BUILD_NUMBER}"
        GITHUB_TOKEN = credentials('Github_cred')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/harsha-ops/ROBOT-APP-CICD.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${DOCKER_IMAGE} ./payment/'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push ${DOCKER_IMAGE}'
            }
        }

        stage('Update k8s manifest') {
            steps {
                sh '''
                export REPO_URL="https://${GITHUB_TOKEN}@github.com/harsha-ops/ROBOT-APP-CICD.git"
                sh updatek8smanifest.sh payment ${DOCKER_IMAGE}
                '''
            }
        }
    }
}