pipeline {
    agent any
    environment {
        DOCKER_IMAGE = ""
        GITHUB_TOKEN = credentials('Github_cred')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/harsha-ops/Simple-Voting-APP-ArgoCD.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE} ./cart/"
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${DOCKER_IMAGE}"
            }
        }
    }
}