apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
        - name: dispatch-pod
          image: harsha6798/robot-app-dispatch-image:6
          ports:
          - containerPort: 80