apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
        - name: loadgen-pod
          image: 
          ports:
          - containerPort: 80