apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
        - name: ratings-pod
        image: 
        ports:
        - containerPort: 80